"""`websec init` — scaffold a `.websec-ignore` from what is ACTUALLY in this repo.

The suppression mechanism existed and worked; nothing surfaced it at the moment it was needed. A
first run on a real repo would report most of its findings in seed data, capacity tests and fixture
dirs, and the operator had to already know that `.websec-ignore` existed, what its syntax was, and
which paths of theirs to put in it (field report #8). Everything before the first useful report.

So this proposes the scoping from evidence rather than from a template: it walks the repo, finds the
directories that look like test/fixture/seed/vendor territory, counts what is in them, and writes a
file where every entry carries the count that justifies it. The operator reads a list of decisions
with their reasons, not a blank file with a link to the docs.

Two deliberate restraints:

  * **Nothing is suppressed silently.** Every proposed line is printed, with its file count, before
    the file is written; `--dry-run` prints without writing. A suppression the operator did not
    read is indistinguishable from a bug.
  * **An existing `.websec-ignore` is never clobbered** without `--force`. It is a policy document —
    possibly with `fingerprint:` acknowledgements someone justified in a review — and regenerating
    it from heuristics would silently discard that reasoning.
"""

from __future__ import annotations

from pathlib import Path

from .extractors.base import RepoContext, SKIP_DIRS, is_script_file, is_test_file

IGNORE_NAME = ".websec-ignore"

# Directory names that are, by near-universal convention, not the product. Each becomes a candidate
# scope ONLY if it actually exists in this repo AND holds files — a proposal for a directory the
# operator does not have is noise, and worse, it teaches them the file is boilerplate.
_CANDIDATE_DIRS = (
    ("tests", "test code"),
    ("test", "test code"),
    ("__tests__", "test code"),
    ("spec", "test code"),
    ("e2e", "end-to-end test code"),
    ("cypress", "end-to-end test code"),
    ("fixtures", "test fixtures — planted fake credentials are normal here"),
    ("__mocks__", "test doubles"),
    ("mocks", "test doubles"),
    ("testdata", "test input data"),
    ("seed", "seed/demo data — fake credentials are the point"),
    ("seeds", "seed/demo data — fake credentials are the point"),
    ("examples", "example code, not shipped"),
    ("example", "example code, not shipped"),
    ("samples", "sample code, not shipped"),
    ("demo", "demo code, not shipped"),
    ("benchmarks", "benchmark harness, not reachable from a request"),
    ("capacity-test", "load/capacity harness, not reachable from a request"),
    ("load-test", "load/capacity harness, not reachable from a request"),
    ("perf", "performance harness, not reachable from a request"),
    ("vendor", "vendored third-party code — scan upstream, not your copy"),
    ("third_party", "vendored third-party code — scan upstream, not your copy"),
)

_HEADER = """\
# .websec-ignore — scope policy for websec-validator
#
# Generated by `websec init` from what is actually in this repository. Every entry below was
# proposed because the directory EXISTS here and holds files; the count on each line is the
# evidence. Read them, delete the ones you disagree with, and commit this file.
#
# Three kinds of line:
#
#   path/glob            a path substring or glob. Findings whose location matches are SUPPRESSED
#                        (they leave the ledger and stop gating). Use for code that is not your
#                        product: tests, fixtures, seed data, vendored copies.
#   category:<name>      suppress a whole finding category, e.g. `category:static-secret`.
#   fingerprint:<id> expires:YYYY-MM-DD  # why
#                        ACKNOWLEDGE one specific finding. It stays VISIBLE in the report and stops
#                        gating until the expiry date. A reason is required. This is the honest
#                        option for a known, accepted risk — prefer it over a path glob, which
#                        hides everything in that path forever, including findings that do not
#                        exist yet.
#
# Suppression is scope, not a verdict: a secret in a fixture is still committed. If you suppress a
# path, you are saying "this is not my product", not "this is safe".
"""

_FOOTER = """
# --- examples, uncomment and edit -------------------------------------------------------------
# category:static-secret               # suppress every static-secret finding (blunt; prefer paths)
# fingerprint:abc123def456 expires:2026-12-31  # accepted: internal-only admin route, tracked in JIRA-123
"""


def _count_files(root: Path, rel_dir: str, limit: int = 5000) -> int:
    """How many files live under this directory — the evidence for proposing it."""
    try:
        base = root / rel_dir
        if not base.is_dir():
            return 0
        n = 0
        for p in base.rglob("*"):
            if n >= limit:
                break
            if p.is_file():
                n += 1
        return n
    except OSError:
        return 0


def propose(target: Path, ctx: RepoContext | None = None) -> dict:
    """Scoping proposals for this repo. Pure analysis — writes nothing.

    Returns {"entries": [{path, reason, files}], "already_exists": bool, "analyzed_files": int}."""
    root = Path(target)
    ctx = ctx or RepoContext(root)
    rels = [ctx.rel(p) for p in (ctx.all_code_files or ctx.code_files)]

    # Find every directory in the tree matching a candidate name, at any depth, so a monorepo's
    # `backend/capacity-test/` is proposed just as readily as a root-level `tests/`.
    seen: dict = {}
    try:
        for path in root.rglob("*"):
            if not path.is_dir():
                continue
            rel = path.relative_to(root).as_posix()
            parts = rel.split("/")
            if any(seg in SKIP_DIRS for seg in parts):
                continue
            if len(parts) > 4:            # keep the walk (and the proposal list) bounded
                continue
            for name, reason in _CANDIDATE_DIRS:
                if parts[-1].lower() != name:
                    continue
                # Do not propose a directory nested inside one we already propose — the parent
                # glob already covers it, and two overlapping rules read as a mistake.
                if any(rel.startswith(prior + "/") for prior in seen):
                    continue
                n = _count_files(root, rel)
                if n:
                    seen[rel] = {"path": f"{rel}/", "reason": reason, "files": n}
                break
    except OSError:
        pass

    entries = sorted(seen.values(), key=lambda e: (-e["files"], e["path"]))
    # How much of the analyzed surface this would take out — the number that tells the operator
    # whether this scoping is reasonable or far too aggressive.
    covered = sum(1 for r in rels if any(r.startswith(e["path"]) for e in entries))
    heuristic = sum(1 for r in rels if is_test_file(r) or is_script_file(r))
    return {"entries": entries, "already_exists": (root / IGNORE_NAME).is_file(),
            "analyzed_files": len(rels), "covered_files": covered,
            "heuristic_nonproduct_files": heuristic}


def render(proposal: dict) -> str:
    lines = [_HEADER]
    if proposal["entries"]:
        lines.append("\n# --- detected in this repository ---------------------------------------------------------\n")
        for e in proposal["entries"]:
            lines.append(f"{e['path']:<52}# {e['reason']} ({e['files']} file(s))\n")
    else:
        lines.append("\n# No test/fixture/seed/vendor directories were detected in this repository, so nothing\n"
                     "# is scoped out by default. Add paths here if a first run reports findings in code that\n"
                     "# is not your product.\n")
    lines.append(_FOOTER)
    return "".join(lines)


def write(target: Path, proposal: dict, *, force: bool = False) -> dict:
    """Write `.websec-ignore`. Refuses to clobber an existing one unless `force`."""
    path = Path(target) / IGNORE_NAME
    if path.is_file() and not force:
        return {"written": False, "path": str(path), "reason": "already exists (use --force to replace)"}
    path.write_text(render(proposal))
    return {"written": True, "path": str(path), "entries": len(proposal["entries"])}
