"""Ownership preservation and executable current-attempt guidance contracts."""
import contextlib
import io
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
from websec_validator import install
from websec_validator.cli import main
from websec_validator.extractors.base import MAX_BYTES


class InstallOwnershipTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)

    def test_foreign_skills_are_never_overwritten_or_removed(self):
        for host in ('claude', 'cursor'):
            dest = self.root / install.HOSTS[host].project_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            for content in (b'# My instructions\r\n', install._skill_frontmatter(host).encode()):
                dest.write_bytes(content)
                for uninstall in (False, True):
                    with self.subTest(host=host, uninstall=uninstall):
                        with self.assertRaisesRegex(ValueError, 'foreign skill'):
                            install.install(host, project_dir=self.root, uninstall=uninstall)
                        self.assertEqual(dest.read_bytes(), content)
                self.assertNotIn('✓ ' + host, install.status(project_dir=self.root))

    def test_older_generated_skills_refresh_and_uninstall(self):
        for host in ('claude', 'cursor'):
            dest = self.root / install.HOSTS[host].project_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            old = (install._skill_frontmatter(host) + '<!-- generated by websec-validator 0.9.0 — '
                   f're-run `websec install {host}` to refresh -->\n\nOld managed guidance.\n')
            dest.write_text(old)
            install.install(host, project_dir=self.root)
            expected = dest.read_bytes()
            self.assertNotIn(b'Old managed guidance', expected)
            install.install(host, project_dir=self.root)
            self.assertEqual(dest.read_bytes(), expected)
            install.install(host, project_dir=self.root, uninstall=True)
            self.assertFalse(dest.exists())

    def test_historical_crlf_skill_is_owned_but_foreign_crlf_is_not(self):
        for host in ('claude', 'cursor'):
            dest = self.root / install.HOSTS[host].project_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            owned = install._skill_content(host).replace('websec-validator ' + install.__version__,
                                                       'websec-validator 0.9.0').replace('\n', '\r\n')
            dest.write_bytes(owned.encode())
            install.install(host, project_dir=self.root)
            self.assertEqual(dest.read_text(), install._skill_content(host))
            dest.write_bytes(owned.encode())
            install.install(host, project_dir=self.root, uninstall=True)
            self.assertFalse(dest.exists())

    def test_ambiguous_marker_shapes_preserve_every_byte(self):
        start, end = install.MARKER_START, install.MARKER_END
        malformed = [start + '\nKeep trailing policy\n', end + '\nKeep policy\n',
                     end + '\n' + start + '\n', start + '\n' + end + '\n' + start + '\n',
                     start + '\n' + end + '\n' + end + '\n',
                     'inline ' + start + '\n' + end + '\n',
                     start + ' inline\n' + end + '\n', start + '\ninline ' + end + '\n',
                     start + '\n' + end + ' inline\n']
        dest = self.root / 'AGENTS.md'
        for shape in malformed:
            content = ('# Keep me\r\n\r\n' + shape + 'Critical policy\r\n').encode()
            dest.write_bytes(content)
            for uninstall in (False, True):
                with self.subTest(shape=shape, uninstall=uninstall):
                    with self.assertRaisesRegex(ValueError, 'ambiguous'):
                        install.install('generic', project_dir=self.root, uninstall=uninstall)
                    self.assertEqual(dest.read_bytes(), content)

    def test_valid_managed_block_preserves_crlf_and_whitespace_surroundings(self):
        dest = self.root / 'AGENTS.md'
        prefix, suffix = b'# Foreign rules\r\n  \r\n', b'\r\nOther policy  \r\n\r\n'
        dest.write_bytes(prefix + install._block_content().encode() + suffix)
        install.install('generic', project_dir=self.root)
        self.assertEqual(dest.read_bytes(), prefix + install._block_content().encode() + suffix)
        install.install('generic', project_dir=self.root, uninstall=True)
        self.assertEqual(dest.read_bytes(), prefix + suffix)

    def test_uninstall_unmanaged_empty_and_whitespace_files_is_noop(self):
        dest = self.root / 'AGENTS.md'
        for content in (b'', b' \r\n\n', b'# Keep me\r\n\r\n'):
            dest.write_bytes(content)
            install.install('generic', project_dir=self.root, uninstall=True)
            self.assertEqual(dest.read_bytes(), content)

    def test_cli_ownership_error_is_actionable_exit_two(self):
        dest = self.root / 'AGENTS.md'
        dest.write_text(install.MARKER_START + '\nKeep me')
        with contextlib.redirect_stderr(io.StringIO()) as err:
            rc = main(['install', 'generic', '--project-dir', str(self.root)])
        self.assertEqual(rc, 2)
        self.assertIn('restore one complete managed block', err.getvalue())
        self.assertEqual(dest.read_text(), install.MARKER_START + '\nKeep me')

    @unittest.skipUnless(hasattr(os, 'mkfifo'), 'requires FIFO')
    def test_special_file_is_refused_without_opening(self):
        dest = self.root / 'AGENTS.md'
        os.mkfifo(dest)
        with self.assertRaisesRegex(ValueError, 'readable regular file'):
            install.install('generic', project_dir=self.root)
        self.assertTrue(dest.exists())


class InstallGuidanceTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.selector = install._INSTRUCTION_BODY.split("<<'PY'\n", 1)[1].split('\nPY\n', 1)[0]

    def select(self, envelope, status=0):
        log = self.root / 'envelope.json'
        log.write_text(envelope if isinstance(envelope, str) else json.dumps(envelope))
        return subprocess.run([sys.executable, '-I', '-c', self.selector,
                               str(self.root / 'out'), str(log), str(status)],
                              capture_output=True, text=True, timeout=15)

    def test_shipped_skill_uses_same_working_selector_and_evidence_contract(self):
        skill = (ROOT / 'skills/security-pass/SKILL.md').read_text()
        self.assertIn(install._INSTRUCTION_BODY, skill)
        self.assertNotIn('pipx upgrade', skill)
        self.assertNotIn('websec-out/AGENT-BRIEFING.md', skill)
        self.assertIn('websec repair-verify --help', skill)
        self.assertIn('HTTP status alone does not prove', skill)
        self.assertIn('source freshness is unverified', skill)

    def test_real_complete_and_partial_attempt_select_exact_directory(self):
        target = self.root / 'target'
        target.mkdir()
        (target / 'app.py').write_text('x=1\n')
        out = self.root / 'out'
        args = ['run', str(target), '--out', str(out), '--format', 'json', '--require-complete']
        with contextlib.redirect_stdout(io.StringIO()) as stdout:
            rc = main(args)
        self.assertEqual(rc, 0)
        complete = json.loads(stdout.getvalue())
        selected = self.select(complete, rc)
        self.assertEqual(selected.returncode, 0, selected.stderr)
        self.assertIn(complete['generated'], selected.stdout)
        previous = (out / 'latest').resolve()
        (target / 'huge.py').write_bytes(b'#' * (MAX_BYTES + 1))
        with contextlib.redirect_stdout(io.StringIO()) as stdout:
            rc = main(args)
        self.assertEqual(rc, 2)
        partial = json.loads(stdout.getvalue())
        self.assertFalse(partial['coverage']['execution_complete'])
        selected = self.select(partial, rc)
        self.assertEqual(selected.returncode, 2, selected.stderr)
        self.assertIn(partial['generated'], selected.stdout)
        self.assertNotIn(complete['generated'], selected.stdout)
        self.assertEqual((out / 'latest').resolve(), previous)

    def test_nested_output_symlinks_cannot_select_external_or_older_artifacts(self):
        out = self.root / 'out'
        out.mkdir()
        external = self.root / 'external'
        external.mkdir()
        (external / 'current').mkdir()
        (out / 'runs').symlink_to(external)
        envelope = {'tool': 'websec-validator', 'schema_version': '2.0',
                    'coverage': {'execution_complete': True}, 'generated': 'current'}
        selected = self.select(envelope)
        self.assertNotEqual(selected.returncode, 0)
        self.assertNotIn('Current run:', selected.stdout)
        (out / 'runs').unlink()
        (out / 'runs').mkdir()
        (out / 'runs' / 'older').mkdir()
        (out / 'runs' / 'current').symlink_to(out / 'runs' / 'older')
        selected = self.select(envelope)
        self.assertNotEqual(selected.returncode, 0)
        self.assertNotIn('Current run:', selected.stdout)

    def test_absent_malformed_escaping_and_missing_attempt_never_select_latest(self):
        runs = self.root / 'out' / 'runs'
        runs.mkdir(parents=True)
        (runs / 'old').mkdir()
        (self.root / 'out' / 'latest').symlink_to(runs / 'old')
        base = {'tool': 'websec-validator', 'schema_version': '2.0', 'coverage': {'execution_complete': True}}
        for envelope in ('', '{}', '[]', {**base, 'generated': '../latest'},
                         {**base, 'generated': 'not-created'}, {**base, 'generated': 'old', 'coverage': None}):
            with self.subTest(envelope=envelope):
                selected = self.select(envelope, 2)
                self.assertNotEqual(selected.returncode, 0)
                self.assertNotIn('Current run:', selected.stdout)
                self.assertIn('do not use latest', selected.stderr)


if __name__ == '__main__':
    unittest.main()
